# Generated by Django 6.0.7 on 2026-08-17 07:04

import django.db.models.deletion
from django.db import migrations, models


def copy_addresses_to_accounts(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute("SELECT count(*) FROM sqlite_master WHERE type='table' AND name='orders_address'")
        if cursor.fetchone()[0] > 0:
            cursor.execute("SELECT id, user_id, full_name, phone, address_line, city, state, pincode, landmark, created_at FROM orders_address")
            rows = cursor.fetchall()
            for row in rows:
                addr_id, user_id, full_name, phone, address_line, city, state, pincode, landmark, created_at = row
                cursor.execute(
                    """
                    INSERT OR IGNORE INTO accounts_address (id, user_id, full_name, phone, address_type, address_line_1, address_line_2, city, state, pincode, landmark, is_default, created_at, updated_at)
                    VALUES (%s, %s, %s, %s, 'home', %s, '', %s, %s, %s, %s, 1, %s, %s)
                    """,
                    [addr_id, user_id, full_name, phone, address_line, city, state, pincode, landmark or '', created_at, created_at]
                )


def populate_shipping_snapshots(apps, schema_editor):
    connection = schema_editor.connection
    with connection.cursor() as cursor:
        cursor.execute(
            """
            UPDATE orders_order
            SET shipping_name = (SELECT full_name FROM accounts_address WHERE accounts_address.id = orders_order.address_id),
                shipping_phone = (SELECT phone FROM accounts_address WHERE accounts_address.id = orders_order.address_id),
                shipping_address = (SELECT address_line_1 FROM accounts_address WHERE accounts_address.id = orders_order.address_id),
                shipping_city = (SELECT city FROM accounts_address WHERE accounts_address.id = orders_order.address_id),
                shipping_state = (SELECT state FROM accounts_address WHERE accounts_address.id = orders_order.address_id),
                shipping_pincode = (SELECT pincode FROM accounts_address WHERE accounts_address.id = orders_order.address_id)
            WHERE address_id IS NOT NULL
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
        ('orders', '0003_alter_order_status'),
    ]

    operations = [
        migrations.RunPython(copy_addresses_to_accounts, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_pincode',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(populate_shipping_snapshots, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='accounts.address'),
        ),
        migrations.DeleteModel(
            name='Address',
        ),
    ]

