# Generated by Django 6.0.7 on 2026-08-04 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
    ]
