# Generated by Django 6.0.7 on 2026-08-12 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_add_initial_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='brand',
            new_name='author',
        ),
    ]
