# Generated by Django 6.0.7 on 2026-08-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_low_stock_threshold_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('out_of_stock', 'Out of Stock'), ('draft', 'Draft')], default='active', max_length=20),
        ),
    ]
